version: '3.7'

services:
  blue:
    build: .
    container_name: blue
    environment:
      - APP_VERSION=Blue

  green:
    build: .
    container_name: green
    environment:
      - APP_VERSION=Green
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      # Mount our config file into the container
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - blue
      - green